/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/ping": {
    get: operations["AppController_ping"];
  };
  "/tenants": {
    get: operations["TenantsController_findAll"];
    put: operations["TenantsController_updateAll"];
    post: operations["TenantsController_create"];
  };
  "/tenants/count": {
    get: operations["TenantsController_count"];
  };
  "/tenants/{id}": {
    get: operations["TenantsController_findOne"];
    put: operations["TenantsController_update"];
    delete: operations["TenantsController_remove"];
  };
  "/tenants/{id}/replace": {
    put: operations["TenantsController_replaceById"];
  };
  "/tenants/{id}/actors": {
    get: operations["TenantsController_findActors"];
  };
  "/tenants/{id}/actor-groups": {
    get: operations["TenantsController_findActorGroups"];
  };
  "/tenants/{id}/process-definitions": {
    get: operations["TenantsController_findProcessDefinitions"];
  };
  "/actor-groups": {
    get: operations["ActorGroupsController_findAll"];
    post: operations["ActorGroupsController_create"];
  };
  "/actor-groups/{id}": {
    get: operations["ActorGroupsController_findOne"];
    put: operations["ActorGroupsController_update"];
    delete: operations["ActorGroupsController_remove"];
  };
  "/actor-groups/{id}/actors": {
    get: operations["ActorGroupsController_findActors"];
    post: operations["ActorGroupsController_createActor"];
    delete: operations["ActorGroupsController_deleteActors"];
    patch: operations["ActorGroupsController_patchActors"];
  };
  "/actors": {
    get: operations["ActorsController_findAll"];
    post: operations["ActorsController_create"];
  };
  "/actors/{id}": {
    get: operations["ActorsController_findOne"];
    put: operations["ActorsController_update"];
    delete: operations["ActorsController_remove"];
  };
  "/process-definitions": {
    get: operations["ProcessDefinitionsController_findAll"];
    post: operations["ProcessDefinitionsController_create"];
  };
  "/process-definitions/{id}": {
    get: operations["ProcessDefinitionsController_findOne"];
    put: operations["ProcessDefinitionsController_update"];
    delete: operations["ProcessDefinitionsController_remove"];
  };
  "/process-definitions/{id}/process-instances": {
    get: operations["ProcessDefinitionsController_findProcessInstances"];
    post: operations["ProcessDefinitionsController_createProcessInstance"];
    delete: operations["ProcessDefinitionsController_deleteProcessInstances"];
    patch: operations["ProcessDefinitionsController_patchProcessInstances"];
  };
  "/process-instances": {
    get: operations["ProcessInstancesController_findAll"];
    post: operations["ProcessInstancesController_create"];
  };
  "/process-instances/{id}": {
    get: operations["ProcessInstancesController_findOne"];
    put: operations["ProcessInstancesController_update"];
    delete: operations["ProcessInstancesController_remove"];
  };
  "/process-instances/{id}/user-task-instances": {
    get: operations["ProcessInstancesController_findUserTaskInstances"];
    post: operations["ProcessInstancesController_createUserTaskInstance"];
    delete: operations["ProcessInstancesController_deleteUserTaskInstances"];
    patch: operations["ProcessInstancesController_patchUserTaskInstances"];
  };
  "/user-task-instances": {
    get: operations["UserTaskInstancesController_findAll"];
    post: operations["UserTaskInstancesController_create"];
  };
  "/user-task-instances/{id}": {
    get: operations["UserTaskInstancesController_findOne"];
    put: operations["UserTaskInstancesController_update"];
    delete: operations["UserTaskInstancesController_remove"];
  };
  "/user-task-instances/{id}/assignee": {
    get: operations["UserTaskInstancesController_findAssignee"];
  };
}

export interface components {
  schemas: {
    CreateTenantDto: {
      name: string;
    };
    UpdateTenantDto: {
      name?: string;
    };
    CreateActorGroupDto: {
      name: string;
      tenantId: string;
    };
    UpdateActorGroupDto: {
      name?: string;
      tenantId?: string;
    };
    CreateActorDto: {
      name: string;
      email: string;
      tenantId: string;
      actorGroupId?: string;
    };
    UpdateActorDto: {
      name?: string;
      email?: string;
      tenantId?: string;
      actorGroupId?: string;
    };
    CreateProcessDefinitionDto: {
      name: string;
      bpmnXml: string;
      tenantId: string;
    };
    UpdateProcessDefinitionDto: {
      name?: string;
      bpmnXml?: string;
      tenantId?: string;
    };
    CreateProcessInstanceDto: {
      status: string;
      variables?: { [key: string]: unknown };
      state?: { [key: string]: unknown };
      tenantId: string;
      processDefinitionId: string;
    };
    UpdateProcessInstanceDto: {
      status?: string;
      variables?: { [key: string]: unknown };
      state?: { [key: string]: unknown };
      tenantId?: string;
      processDefinitionId?: string;
    };
    CreateUserTaskInstanceDto: {
      taskId: string;
      status: string;
      tenantId: string;
      processInstanceId: string;
      assigneeId?: string;
    };
    UpdateUserTaskInstanceDto: {
      taskId?: string;
      status?: string;
      tenantId?: string;
      processInstanceId?: string;
      assigneeId?: string;
    };
  };
}

export interface operations {
  AppController_getHello: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  AppController_ping: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  TenantsController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  TenantsController_updateAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTenantDto"];
      };
    };
  };
  TenantsController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTenantDto"];
      };
    };
  };
  TenantsController_count: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  TenantsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  TenantsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTenantDto"];
      };
    };
  };
  TenantsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  TenantsController_replaceById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTenantDto"];
      };
    };
  };
  TenantsController_findActors: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  TenantsController_findActorGroups: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  TenantsController_findProcessDefinitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ActorGroupsController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  ActorGroupsController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActorGroupDto"];
      };
    };
  };
  ActorGroupsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ActorGroupsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActorGroupDto"];
      };
    };
  };
  ActorGroupsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ActorGroupsController_findActors: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ActorGroupsController_createActor: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActorDto"];
      };
    };
  };
  ActorGroupsController_deleteActors: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ActorGroupsController_patchActors: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActorDto"];
      };
    };
  };
  ActorsController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  ActorsController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActorDto"];
      };
    };
  };
  ActorsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ActorsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActorDto"];
      };
    };
  };
  ActorsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessDefinitionsController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  ProcessDefinitionsController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProcessDefinitionDto"];
      };
    };
  };
  ProcessDefinitionsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessDefinitionsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProcessDefinitionDto"];
      };
    };
  };
  ProcessDefinitionsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessDefinitionsController_findProcessInstances: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessDefinitionsController_createProcessInstance: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProcessInstanceDto"];
      };
    };
  };
  ProcessDefinitionsController_deleteProcessInstances: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessDefinitionsController_patchProcessInstances: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProcessInstanceDto"];
      };
    };
  };
  ProcessInstancesController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  ProcessInstancesController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProcessInstanceDto"];
      };
    };
  };
  ProcessInstancesController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessInstancesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProcessInstanceDto"];
      };
    };
  };
  ProcessInstancesController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessInstancesController_findUserTaskInstances: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessInstancesController_createUserTaskInstance: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserTaskInstanceDto"];
      };
    };
  };
  ProcessInstancesController_deleteUserTaskInstances: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  ProcessInstancesController_patchUserTaskInstances: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserTaskInstanceDto"];
      };
    };
  };
  UserTaskInstancesController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  UserTaskInstancesController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserTaskInstanceDto"];
      };
    };
  };
  UserTaskInstancesController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UserTaskInstancesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserTaskInstanceDto"];
      };
    };
  };
  UserTaskInstancesController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UserTaskInstancesController_findAssignee: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
}

export interface external {}
