/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/actor-groups/{id}/actors": {
    get: operations["ActorGroupActorController.find"];
    post: operations["ActorGroupActorController.create"];
    delete: operations["ActorGroupActorController.delete"];
    patch: operations["ActorGroupActorController.patch"];
  };
  "/ping": {
    get: operations["PingController.ping"];
  };
  "/process-definitions/{id}/process-instances": {
    get: operations["ProcessDefinitionProcessInstanceController.find"];
    post: operations["ProcessDefinitionProcessInstanceController.create"];
    delete: operations["ProcessDefinitionProcessInstanceController.delete"];
    patch: operations["ProcessDefinitionProcessInstanceController.patch"];
  };
  "/process-definitions/{id}/start": {
    post: operations["ProcessInstanceController.start"];
  };
  "/process-definitions/{id}": {
    get: operations["ProcessDefinitionController.findById"];
    put: operations["ProcessDefinitionController.replaceById"];
    delete: operations["ProcessDefinitionController.deleteById"];
  };
  "/process-definitions": {
    get: operations["ProcessDefinitionController.find"];
    post: operations["ProcessDefinitionController.create"];
  };
  "/process-instances/{id}/user-task-instances": {
    get: operations["ProcessInstanceUserTaskInstanceController.find"];
    post: operations["ProcessInstanceUserTaskInstanceController.create"];
    delete: operations["ProcessInstanceUserTaskInstanceController.delete"];
    patch: operations["ProcessInstanceUserTaskInstanceController.patch"];
  };
  "/tenants/count": {
    get: operations["TenantController.count"];
  };
  "/tenants/{id}/actor-groups": {
    get: operations["TenantActorGroupController.find"];
  };
  "/tenants/{id}/actors": {
    get: operations["TenantActorController.find"];
  };
  "/tenants/{id}/process-definitions": {
    get: operations["TenantProcessDefinitionController.find"];
  };
  "/tenants/{id}": {
    get: operations["TenantController.findById"];
    put: operations["TenantController.replaceById"];
    delete: operations["TenantController.deleteById"];
    patch: operations["TenantController.updateById"];
  };
  "/tenants": {
    get: operations["TenantController.find"];
    post: operations["TenantController.create"];
    patch: operations["TenantController.updateAll"];
  };
  "/user-task-instances/{id}/actor": {
    get: operations["UserTaskInstanceActorController.getActor"];
  };
}

export interface components {
  schemas: {
    /** Actor */
    Actor: {
      id?: string;
      name: string;
      email: string;
      actorGroupId?: string;
      tenantId?: string;
    };
    /** Tenant */
    Tenant: {
      id?: string;
      name: string;
    };
    /**
     * NewTenant
     * @description (tsType: Omit<Tenant, 'id'>, schemaOptions: { title: 'NewTenant', exclude: [ 'id' ] })
     */
    NewTenant: {
      name: string;
    };
    /**
     * ActorWithRelations
     * @description (tsType: ActorWithRelations, schemaOptions: { includeRelations: true })
     */
    ActorWithRelations: {
      id?: string;
      name: string;
      email: string;
      actorGroupId?: string;
      tenantId?: string;
      tenant?: components["schemas"]["TenantWithRelations"];
      foreignKey?: unknown;
    };
    /**
     * UserTaskInstanceWithRelations
     * @description (tsType: UserTaskInstanceWithRelations, schemaOptions: { includeRelations: true })
     */
    UserTaskInstanceWithRelations: {
      id?: string;
      instanceId: string;
      taskId: string;
      assigneeId?: string;
      status: string;
      tenantId?: string;
      processInstanceId?: string;
      actorId?: string;
      tenant?: components["schemas"]["TenantWithRelations"];
      foreignKey?: unknown;
      assignee?: components["schemas"]["ActorWithRelations"];
    };
    /**
     * ProcessInstanceWithRelations
     * @description (tsType: ProcessInstanceWithRelations, schemaOptions: { includeRelations: true })
     */
    ProcessInstanceWithRelations: {
      id?: string;
      definitionId: string;
      status: string;
      variables?: { [key: string]: unknown };
      state?: { [key: string]: unknown };
      tenantId?: string;
      processDefinitionId?: string;
      tenant?: components["schemas"]["TenantWithRelations"];
      foreignKey?: unknown;
      userTaskInstances?: components["schemas"]["UserTaskInstanceWithRelations"][];
    };
    /**
     * ProcessDefinitionWithRelations
     * @description (tsType: ProcessDefinitionWithRelations, schemaOptions: { includeRelations: true })
     */
    ProcessDefinitionWithRelations: {
      id?: string;
      name: string;
      bpmnXml: string;
      tenantId?: string;
      tenant?: components["schemas"]["TenantWithRelations"];
      foreignKey?: unknown;
      processInstances?: components["schemas"]["ProcessInstanceWithRelations"][];
    };
    /**
     * ActorGroupWithRelations
     * @description (tsType: ActorGroupWithRelations, schemaOptions: { includeRelations: true })
     */
    ActorGroupWithRelations: {
      id?: string;
      name: string;
      tenantId?: string;
      tenant?: components["schemas"]["TenantWithRelations"];
      foreignKey?: unknown;
      actors?: components["schemas"]["ActorWithRelations"][];
    };
    /**
     * TenantWithRelations
     * @description (tsType: TenantWithRelations, schemaOptions: { includeRelations: true })
     */
    TenantWithRelations: {
      id?: string;
      name: string;
      processDefinitions?: components["schemas"]["ProcessDefinitionWithRelations"][];
      actors?: components["schemas"]["ActorWithRelations"][];
      actorGroups?: components["schemas"]["ActorGroupWithRelations"][];
      processInstances?: components["schemas"]["ProcessInstanceWithRelations"][];
      userTaskInstances?: components["schemas"]["UserTaskInstanceWithRelations"][];
    };
    /**
     * TenantPartial
     * @description (tsType: Partial<Tenant>, schemaOptions: { partial: true })
     */
    TenantPartial: {
      id?: string;
      name?: string;
    };
    /** ProcessDefinition */
    ProcessDefinition: {
      id?: string;
      name: string;
      bpmnXml: string;
      tenantId?: string;
    };
    /** ActorGroup */
    ActorGroup: {
      id?: string;
      name: string;
      tenantId?: string;
    };
    /** ProcessInstance */
    ProcessInstance: {
      id?: string;
      definitionId: string;
      status: string;
      variables?: { [key: string]: unknown };
      state?: { [key: string]: unknown };
      tenantId?: string;
      processDefinitionId?: string;
    };
    /** UserTaskInstance */
    UserTaskInstance: {
      id?: string;
      instanceId: string;
      taskId: string;
      assigneeId?: string;
      status: string;
      tenantId?: string;
      processInstanceId?: string;
      actorId?: string;
    };
    /**
     * NewUserTaskInstanceInProcessInstance
     * @description (tsType: @loopback/repository-json-schema#Optional<Omit<UserTaskInstance, 'id'>, 'processInstanceId'>, schemaOptions: { title: 'NewUserTaskInstanceInProcessInstance', exclude: [ 'id' ], optional: [ 'processInstanceId' ] })
     */
    NewUserTaskInstanceInProcessInstance: {
      instanceId: string;
      taskId: string;
      assigneeId?: string;
      status: string;
      tenantId?: string;
      processInstanceId?: string;
      actorId?: string;
    };
    /**
     * UserTaskInstancePartial
     * @description (tsType: Partial<UserTaskInstance>, schemaOptions: { partial: true })
     */
    UserTaskInstancePartial: {
      id?: string;
      instanceId?: string;
      taskId?: string;
      assigneeId?: string;
      status?: string;
      tenantId?: string;
      processInstanceId?: string;
      actorId?: string;
    };
    /**
     * NewProcessDefinition
     * @description (tsType: Omit<ProcessDefinition, 'id'>, schemaOptions: { title: 'NewProcessDefinition', exclude: [ 'id' ] })
     */
    NewProcessDefinition: {
      name: string;
      bpmnXml: string;
      tenantId?: string;
    };
    /**
     * NewProcessInstanceInProcessDefinition
     * @description (tsType: @loopback/repository-json-schema#Optional<Omit<ProcessInstance, 'id'>, 'processDefinitionId'>, schemaOptions: { title: 'NewProcessInstanceInProcessDefinition', exclude: [ 'id' ], optional: [ 'processDefinitionId' ] })
     */
    NewProcessInstanceInProcessDefinition: {
      definitionId: string;
      status: string;
      variables?: { [key: string]: unknown };
      state?: { [key: string]: unknown };
      tenantId?: string;
      processDefinitionId?: string;
    };
    /**
     * ProcessInstancePartial
     * @description (tsType: Partial<ProcessInstance>, schemaOptions: { partial: true })
     */
    ProcessInstancePartial: {
      id?: string;
      definitionId?: string;
      status?: string;
      variables?: { [key: string]: unknown };
      state?: { [key: string]: unknown };
      tenantId?: string;
      processDefinitionId?: string;
    };
    /**
     * NewActorInActorGroup
     * @description (tsType: @loopback/repository-json-schema#Optional<Omit<Actor, 'id'>, 'actorGroupId'>, schemaOptions: { title: 'NewActorInActorGroup', exclude: [ 'id' ], optional: [ 'actorGroupId' ] })
     */
    NewActorInActorGroup: {
      name: string;
      email: string;
      actorGroupId?: string;
      tenantId?: string;
    };
    /**
     * ActorPartial
     * @description (tsType: Partial<Actor>, schemaOptions: { partial: true })
     */
    ActorPartial: {
      id?: string;
      name?: string;
      email?: string;
      actorGroupId?: string;
      tenantId?: string;
    };
    /** loopback.Count */
    "loopback.Count": {
      count?: number;
    };
    /** PingResponse */
    PingResponse: {
      greeting?: string;
      date?: string;
      url?: string;
      headers?: {
        "Content-Type"?: string;
      } & { [key: string]: unknown };
    };
    /** ProcessDefinition.ScopeFilter */
    "ProcessDefinition.ScopeFilter": {
      offset?: number;
      /** @example 100 */
      limit?: number;
      skip?: number;
      order?: string | string[];
      where?: { [key: string]: unknown };
      fields?: { [key: string]: unknown } | string[];
      include?: { [key: string]: unknown }[];
    };
    /** ProcessDefinition.IncludeFilter.Items */
    "ProcessDefinition.IncludeFilter.Items": {
      /** @enum {string} */
      relation?: "tenant" | "processInstances";
      scope?: components["schemas"]["ProcessDefinition.ScopeFilter"];
    };
    /** ProcessDefinition.Filter */
    "ProcessDefinition.Filter": {
      offset?: number;
      /** @example 100 */
      limit?: number;
      skip?: number;
      order?: string | string[];
      /** ProcessDefinition.Fields */
      fields?:
        | {
            id?: boolean;
            name?: boolean;
            bpmnXml?: boolean;
            tenantId?: boolean;
          }
        | ("id" | "name" | "bpmnXml" | "tenantId")[];
      /** ProcessDefinition.IncludeFilter */
      include?: (Partial<
        components["schemas"]["ProcessDefinition.IncludeFilter.Items"]
      > &
        Partial<string>)[];
    };
    /** ProcessDefinition.Filter */
    "ProcessDefinition.Filter1": {
      offset?: number;
      /** @example 100 */
      limit?: number;
      skip?: number;
      order?: string | string[];
      /** ProcessDefinition.WhereFilter */
      where?: { [key: string]: unknown };
      /** ProcessDefinition.Fields */
      fields?:
        | {
            id?: boolean;
            name?: boolean;
            bpmnXml?: boolean;
            tenantId?: boolean;
          }
        | ("id" | "name" | "bpmnXml" | "tenantId")[];
      /** ProcessDefinition.IncludeFilter */
      include?: (Partial<
        components["schemas"]["ProcessDefinition.IncludeFilter.Items"]
      > &
        Partial<string>)[];
    };
    /** Tenant.ScopeFilter */
    "Tenant.ScopeFilter": {
      offset?: number;
      /** @example 100 */
      limit?: number;
      skip?: number;
      order?: string | string[];
      where?: { [key: string]: unknown };
      fields?: { [key: string]: unknown } | string[];
      include?: { [key: string]: unknown }[];
    };
    /** Tenant.IncludeFilter.Items */
    "Tenant.IncludeFilter.Items": {
      /** @enum {string} */
      relation?:
        | "processDefinitions"
        | "actors"
        | "actorGroups"
        | "processInstances"
        | "userTaskInstances";
      scope?: components["schemas"]["Tenant.ScopeFilter"];
    };
    /** Tenant.Filter */
    "Tenant.Filter": {
      offset?: number;
      /** @example 100 */
      limit?: number;
      skip?: number;
      order?: string | string[];
      /** Tenant.Fields */
      fields?:
        | {
            id?: boolean;
            name?: boolean;
          }
        | ("id" | "name")[];
      /** Tenant.IncludeFilter */
      include?: (Partial<components["schemas"]["Tenant.IncludeFilter.Items"]> &
        Partial<string>)[];
    };
    /** Tenant.Filter */
    "Tenant.Filter1": {
      offset?: number;
      /** @example 100 */
      limit?: number;
      skip?: number;
      order?: string | string[];
      /** Tenant.WhereFilter */
      where?: { [key: string]: unknown };
      /** Tenant.Fields */
      fields?:
        | {
            id?: boolean;
            name?: boolean;
          }
        | ("id" | "name")[];
      /** Tenant.IncludeFilter */
      include?: (Partial<components["schemas"]["Tenant.IncludeFilter.Items"]> &
        Partial<string>)[];
    };
  };
}

export interface operations {
  "ActorGroupActorController.find": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** Array of ActorGroup has many Actor */
      200: {
        content: {
          "application/json": components["schemas"]["Actor"][];
        };
      };
    };
  };
  "ActorGroupActorController.create": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** ActorGroup model instance */
      200: {
        content: {
          "application/json": components["schemas"]["Actor"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewActorInActorGroup"];
      };
    };
  };
  "ActorGroupActorController.delete": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** ActorGroup.Actor DELETE success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
  };
  "ActorGroupActorController.patch": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** ActorGroup.Actor PATCH success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActorPartial"];
      };
    };
  };
  "PingController.ping": {
    responses: {
      /** Ping Response */
      200: {
        content: {
          "application/json": components["schemas"]["PingResponse"];
        };
      };
    };
  };
  "ProcessDefinitionProcessInstanceController.find": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** Array of ProcessDefinition has many ProcessInstance */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessInstance"][];
        };
      };
    };
  };
  "ProcessDefinitionProcessInstanceController.create": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** ProcessDefinition model instance */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessInstance"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewProcessInstanceInProcessDefinition"];
      };
    };
  };
  "ProcessDefinitionProcessInstanceController.delete": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** ProcessDefinition.ProcessInstance DELETE success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
  };
  "ProcessDefinitionProcessInstanceController.patch": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** ProcessDefinition.ProcessInstance PATCH success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessInstancePartial"];
      };
    };
  };
  "ProcessInstanceController.start": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** The newly created ProcessInstance */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessInstance"];
        };
      };
    };
    /** Initial variables for the process instance */
    requestBody: {
      content: {
        "application/json": {
          variables?: { [key: string]: unknown };
        };
      };
    };
  };
  "ProcessDefinitionController.findById": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** ProcessDefinition model instance */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessDefinitionWithRelations"];
        };
      };
    };
  };
  "ProcessDefinitionController.replaceById": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: {
        content: {
          "application/json": unknown;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessDefinition"];
      };
    };
  };
  "ProcessDefinitionController.deleteById": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  "ProcessDefinitionController.find": {
    parameters: {
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** Array of ProcessDefinition model instances */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessDefinitionWithRelations"][];
        };
      };
    };
  };
  "ProcessDefinitionController.create": {
    responses: {
      /** ProcessDefinition model instance */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessDefinition"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewProcessDefinition"];
      };
    };
  };
  "ProcessInstanceUserTaskInstanceController.find": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** Array of ProcessInstance has many UserTaskInstance */
      200: {
        content: {
          "application/json": components["schemas"]["UserTaskInstance"][];
        };
      };
    };
  };
  "ProcessInstanceUserTaskInstanceController.create": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** ProcessInstance model instance */
      200: {
        content: {
          "application/json": components["schemas"]["UserTaskInstance"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewUserTaskInstanceInProcessInstance"];
      };
    };
  };
  "ProcessInstanceUserTaskInstanceController.delete": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** ProcessInstance.UserTaskInstance DELETE success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
  };
  "ProcessInstanceUserTaskInstanceController.patch": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** ProcessInstance.UserTaskInstance PATCH success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserTaskInstancePartial"];
      };
    };
  };
  "TenantController.count": {
    parameters: {
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** Tenant model count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
  };
  "TenantActorGroupController.find": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Array of ActorGroup instances belonging to Tenant */
      200: {
        content: {
          "application/json": components["schemas"]["ActorGroup"][];
        };
      };
    };
  };
  "TenantActorController.find": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Array of Actor instances belonging to Tenant */
      200: {
        content: {
          "application/json": components["schemas"]["Actor"][];
        };
      };
    };
  };
  "TenantProcessDefinitionController.find": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Array of ProcessDefinition instances belonging to Tenant */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessDefinition"][];
        };
      };
    };
  };
  "TenantController.findById": {
    parameters: {
      path: {
        id: string;
      };
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** Tenant model instance */
      200: {
        content: {
          "application/json": components["schemas"]["TenantWithRelations"];
        };
      };
    };
  };
  "TenantController.replaceById": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: {
        content: {
          "application/json": unknown;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Tenant"];
      };
    };
  };
  "TenantController.deleteById": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  "TenantController.updateById": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: {
        content: {
          "application/json": unknown;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantPartial"];
      };
    };
  };
  "TenantController.find": {
    parameters: {
      query: {
        filter?: unknown;
      };
    };
    responses: {
      /** Array of Tenant model instances */
      200: {
        content: {
          "application/json": components["schemas"]["TenantWithRelations"][];
        };
      };
    };
  };
  "TenantController.create": {
    responses: {
      /** Tenant model instance */
      200: {
        content: {
          "application/json": components["schemas"]["Tenant"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewTenant"];
      };
    };
  };
  "TenantController.updateAll": {
    parameters: {
      query: {
        where?: unknown;
      };
    };
    responses: {
      /** Tenant PATCH success count */
      200: {
        content: {
          "application/json": components["schemas"]["loopback.Count"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantPartial"];
      };
    };
  };
  "UserTaskInstanceActorController.getActor": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Actor belonging to UserTaskInstance */
      200: {
        content: {
          "application/json": components["schemas"]["Actor"];
        };
      };
    };
  };
}

export interface external {}
