import {
  Count,
  CountSchema,
  Filter,
  FilterExcludingWhere,
  repository,
  Where,
} from '@loopback/repository';
import {
  post,
  param,
  get,
  getModelSchemaRef,
  patch,
  put,
  del,
  requestBody,
  response,
} from '@loopback/rest';
import {ProcessDefinition} from '../models';
import {ProcessDefinitionRepository} from '../repositories';

// Note: For now, we will not add security. We will add authentication
// and multi-tenancy filtering in a later step.

export class ProcessDefinitionController {
  constructor(
    @repository(ProcessDefinitionRepository)
    public processDefinitionRepository: ProcessDefinitionRepository,
  ) {}

  /**
   * Endpoint to create a new process definition.
   * This is used by your bpmn-js frontend when a user creates a new workflow.
   * @param processDefinition The data for the new definition, including name and bpmnXml.
   */
  @post('/process-definitions')
  @response(200, {
    description: 'ProcessDefinition model instance',
    content: {'application/json': {schema: getModelSchemaRef(ProcessDefinition)}},
  })
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(ProcessDefinition, {
            title: 'NewProcessDefinition',
            exclude: ['id'], // The ID is generated by the database
          }),
        },
      },
    })
    processDefinition: Omit<ProcessDefinition, 'id'>,
  ): Promise<ProcessDefinition> {
    // For now, we'll hardcode a tenantId. Later, this will come from the logged-in user's JWT.
    processDefinition.tenantId = 'default-tenant';
    return this.processDefinitionRepository.create(processDefinition);
  }

  /**
   * Endpoint to list all process definitions for the current tenant.
   */
  @get('/process-definitions')
  @response(200, {
    description: 'Array of ProcessDefinition model instances',
    content: {
      'application/json': {
        schema: {
          type: 'array',
          items: getModelSchemaRef(ProcessDefinition, {includeRelations: true}),
        },
      },
    },
  })
  async find(
    @param.filter(ProcessDefinition) filter?: Filter<ProcessDefinition>,
  ): Promise<ProcessDefinition[]> {
    // We will add the tenantId filter here later.
    return this.processDefinitionRepository.find(filter);
  }

  /**
   * Endpoint to get a specific process definition by its ID.
   * This is what your bpmn-js frontend will call to load a workflow into the editor.
   * @param id The ID of the process definition.
   */
  @get('/process-definitions/{id}')
  @response(200, {
    description: 'ProcessDefinition model instance',
    content: {
      'application/json': {
        schema: getModelSchemaRef(ProcessDefinition, {includeRelations: true}),
      },
    },
  })
  async findById(
    @param.path.string('id') id: string,
    @param.filter(ProcessDefinition, {exclude: 'where'})
    filter?: FilterExcludingWhere<ProcessDefinition>,
  ): Promise<ProcessDefinition> {
    // We will add a tenantId check here later.
    return this.processDefinitionRepository.findById(id, filter);
  }

  /**
   * Endpoint to update a process definition.
   * This is the "save" action from your bpmn-js editor.
   * @param id The ID of the process definition to update.
   * @param processDefinition The updated data, including the new bpmnXml.
   */
  @put('/process-definitions/{id}')
  @response(204, {
    description: 'ProcessDefinition PUT success',
  })
  async replaceById(
    @param.path.string('id') id: string,
    @requestBody() processDefinition: ProcessDefinition,
  ): Promise<void> {
    // We will add a tenantId check here later.
    await this.processDefinitionRepository.replaceById(id, processDefinition);
  }

  /**
   * Endpoint to delete a process definition.
   * @param id The ID of the process definition to delete.
   */
  @del('/process-definitions/{id}')
  @response(204, {
    description: 'ProcessDefinition DELETE success',
  })
  async deleteById(@param.path.string('id') id: string): Promise<void> {
    // We will add a tenantId check here later.
    await this.processDefinitionRepository.deleteById(id);
  }
}
