/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BpmnViewerRouteImport } from './routes/bpmn/viewer'
import { Route as BpmnEditorRouteImport } from './routes/bpmn/editor'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BpmnViewerRoute = BpmnViewerRouteImport.update({
  id: '/bpmn/viewer',
  path: '/bpmn/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const BpmnEditorRoute = BpmnEditorRouteImport.update({
  id: '/bpmn/editor',
  path: '/bpmn/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bpmn/editor': typeof BpmnEditorRoute
  '/bpmn/viewer': typeof BpmnViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bpmn/editor': typeof BpmnEditorRoute
  '/bpmn/viewer': typeof BpmnViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bpmn/editor': typeof BpmnEditorRoute
  '/bpmn/viewer': typeof BpmnViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/bpmn/editor' | '/bpmn/viewer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/bpmn/editor' | '/bpmn/viewer'
  id: '__root__' | '/' | '/about' | '/bpmn/editor' | '/bpmn/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BpmnEditorRoute: typeof BpmnEditorRoute
  BpmnViewerRoute: typeof BpmnViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpmn/viewer': {
      id: '/bpmn/viewer'
      path: '/bpmn/viewer'
      fullPath: '/bpmn/viewer'
      preLoaderRoute: typeof BpmnViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpmn/editor': {
      id: '/bpmn/editor'
      path: '/bpmn/editor'
      fullPath: '/bpmn/editor'
      preLoaderRoute: typeof BpmnEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BpmnEditorRoute: BpmnEditorRoute,
  BpmnViewerRoute: BpmnViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
